# docker network create vickze-cloud-admin
# 启动nacos、mysql、redis在同一个网络vickze-cloud-admin

# ./mvnw install -DskipTests
# mkdir -p vickze-gateway/target/dependency && (cd vickze-gateway/target/dependency; jar -xf ../*.jar)
# mkdir -p vickze-auth/vickze-auth-server/target/dependency && (cd vickze-auth/vickze-auth-server/target/dependency; jar -xf ../*.jar)
# mkdir -p vickze-generator/target/dependency && (cd vickze-generator/target/dependency; jar -xf ../*.jar)
# mkdir -p vickze-sso/target/dependency && (cd vickze-sso/target/dependency; jar -xf ../*.jar)
#
# (cd ../vickze-auth-ui/; yarn install; yarn cross-env SSO=http://192.168.244.137:82/ umi build)
# (cd ../vickze-generator-ui/; yarn install; yarn cross-env SSO=http://192.168.244.137:82/ umi build)
# (cd ../vickze-sso-ui/; yarn install; yarn build)
#
# docker-compose -f docker-compose-sso.yml build
# docker-compose -f docker-compose-sso.yml up
version: '2'
networks:
  default:
    external:
      name: vickze-cloud-admin

services:
  vickze-gateway:
    image: io.vickze/vickze-gateway
    build: ./vickze-gateway/
    container_name: vickze-gateway
    volumes:
      - /usr/local/log:/log #挂载日志目录，注意存在Docker容器没有执行权限问题，参考https://www.linuxidc.com/Linux/2015-03/115124.htm解决
      - /etc/localtime:/etc/localtime #解决Docker容器时间与宿主机不一致问题
    ports:
      - "16000:16000"
    environment:
      - NACOS_ADDR=nacos-standalone:8848
      - JAVA_OPTS=-Xmx128m -Duser.timezone=GMT+8 #-Duser.timezone=GMT+8解决打印日志小8小时问题
      - COMMAND_ARGS=--REDIS_HOST=redis
  vickze-auth:
    image: io.vickze/vickze-auth
    build: ./vickze-auth/vickze-auth-server/
    volumes:
      - /usr/local/log:/log
      - /etc/localtime:/etc/localtime
    environment:
      - NACOS_ADDR=nacos-standalone:8848
      - JAVA_OPTS=-Xmx128m -DMYSQL_HOST=mysql -Duser.timezone=GMT+8
      - COMMAND_ARGS=--REDIS_HOST=redis
  vickze-generator:
    image: io.vickze/vickze-generator
    build: ./vickze-generator/
    volumes:
      - /usr/local/log:/log
      - /etc/localtime:/etc/localtime
    environment:
      - NACOS_ADDR=nacos-standalone:8848
      - JAVA_OPTS=-Xmx128m -DMASTER_MYSQL_HOST=mysql -Duser.timezone=GMT+8
      - COMMAND_ARGS=--GENERATOR_MYSQL_HOST=mysql
  vickze-sso:
    image: io.vickze/vickze-sso
    build: ./vickze-sso/
    environment:
      - NACOS_ADDR=nacos-standalone:8848
      - JAVA_OPTS=-Xmx128m -Duser.timezone=GMT+8
  vickze-auth-ui:
    image: io.vickze/vickze-auth-ui
    volumes:
      - /etc/localtime:/etc/localtime
    build:
      context: ../vickze-auth-ui
      dockerfile: Dockerfile.hub
    container_name: vickze-auth-ui
    ports:
      - "80:80"
  vickze-generator-ui:
    image: io.vickze/vickze-generator-ui
    volumes:
      - /etc/localtime:/etc/localtime
    build:
      context: ../vickze-generator-ui
      dockerfile: Dockerfile.hub
    container_name: vickze-generator-ui
    ports:
      - "81:80"
  vickze-sso-ui:
    image: io.vickze/vickze-sso-ui
    volumes:
      - /etc/localtime:/etc/localtime
    build:
      context: ../vickze-sso-ui
      dockerfile: Dockerfile.hub
    container_name: vickze-sso-ui
    ports:
      - "82:80"
